from __future__ import annotations

from typing import Any


def narrative_source_capabilities(
    last_acceptance_status: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    statuses = last_acceptance_status or {}
    return [
        {
            "source_id": "official_filings",
            "provider": "sec_edgar",
            "route": "/api/v1/market-data/narrative/source-events/official-filings",
            "direct_route": "/api/v1/market-data/source-events/official-filings",
            "status": "available",
            "enabled_by_default": True,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "trusted_fact",
            "license_scope": "public_filing",
            "retention_policy": "metadata_and_raw_payload",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("official_filings", "not_run"),
            "known_limitations": "SEC EDGAR metadata fetch depends on public upstream availability.",
        },
        {
            "source_id": "official_disclosures",
            "provider": "cninfo",
            "route": "/api/v1/market-data/narrative/source-events/official-disclosures",
            "direct_route": "/api/v1/market-data/source-events/official-disclosures",
            "status": "available",
            "enabled_by_default": True,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "trusted_fact",
            "license_scope": "public_disclosure_metadata",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("official_disclosures", "not_run"),
            "known_limitations": "CNINFO coverage depends on upstream announcement availability and symbol validity.",
        },
        {
            "source_id": "news_context",
            "provider": "tushare",
            "route": "/api/v1/market-data/narrative/source-events/news-context",
            "direct_route": "/api/v1/market-data/source-events/news-context",
            "status": "permission_dependent",
            "enabled_by_default": True,
            "credential_required": True,
            "permission_probe_available": True,
            "trust_tier": "context_only",
            "license_scope": "context_only",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("news_context", "not_run"),
            "known_limitations": "Tushare news requires token permission and is context only, not trusted fact.",
        },
        {
            "source_id": "official_sources",
            "provider": "official_feed",
            "route": "/api/v1/market-data/source-events/official-sources",
            "direct_route": "/api/v1/market-data/source-events/official-sources",
            "status": "available",
            "enabled_by_default": True,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "trusted_fact",
            "license_scope": "public_official_metadata",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("official_sources", "not_run"),
            "known_limitations": (
                "Only enabled registry feeds are fetched; unknown or disabled official pages are listed "
                "but not fetched by default."
            ),
        },
        {
            "source_id": "official_source_registry",
            "provider": "local_registry",
            "route": "/api/v1/market-data/source-events/official-source-registry",
            "direct_route": "/api/v1/market-data/source-events/official-source-registry",
            "status": "available",
            "enabled_by_default": True,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "registry",
            "license_scope": "registry_metadata",
            "retention_policy": "metadata_only",
            "cache_policy": "no_upstream_fetch",
            "last_acceptance_status": statuses.get("official_source_registry", "not_run"),
            "known_limitations": (
                "Registry seed pack is intentionally small and is not an exhaustive official source catalog."
            ),
        },
        {
            "source_id": "open_news_index",
            "provider": "gdelt",
            "route": "/api/v1/market-data/source-events/open-news-index",
            "direct_route": "/api/v1/market-data/source-events/open-news-index",
            "status": "experimental",
            "enabled_by_default": False,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "context_only",
            "license_scope": "public_news_index_metadata",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("open_news_index", "not_run"),
            "known_limitations": (
                "GDELT is open news-index metadata only and may return rate-limit or non-JSON degraded responses."
            ),
        },
        {
            "source_id": "industry_media",
            "provider": "official_feed",
            "route": "/api/v1/market-data/source-events/industry-media",
            "direct_route": "/api/v1/market-data/source-events/industry-media",
            "status": "pilot",
            "enabled_by_default": True,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "research_context",
            "license_scope": "public_context_metadata",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key",
            "last_acceptance_status": statuses.get("industry_media", "not_run"),
            "known_limitations": (
                "Small allowlisted RSS pilot only; no broad crawling, paywall access, or browser automation."
            ),
        },
        {
            "source_id": "social_heat",
            "provider": "stocktwits",
            "route": "/api/v1/market-data/narrative/source-events/social-heat",
            "direct_route": "/api/v1/market-data/source-events/social-heat",
            "status": "disabled_by_default",
            "enabled_by_default": False,
            "credential_required": False,
            "permission_probe_available": False,
            "trust_tier": "heat_signal_only",
            "license_scope": "public_context",
            "retention_policy": "metadata_only",
            "cache_policy": "sqlite_source_events_by_route_request_key_when_live_enabled",
            "last_acceptance_status": statuses.get(
                "social_heat",
                statuses.get("social_heat_disabled", statuses.get("social_heat_live", "not_run")),
            ),
            "known_limitations": "Stocktwits 默认不启用 live upstream；只可作为热度信号，不能作为事实来源。",
        },
        {
            "source_id": "news_permission_smoke",
            "provider": "tushare",
            "route": "/api/v1/market-data/source-events/news-permission-smoke",
            "direct_route": "/api/v1/market-data/source-events/news-permission-smoke",
            "status": "diagnostic",
            "enabled_by_default": True,
            "credential_required": True,
            "permission_probe_available": True,
            "trust_tier": "diagnostic",
            "license_scope": "diagnostic_only",
            "retention_policy": "no_payload_retention",
            "cache_policy": "no_cache_permission_probe",
            "last_acceptance_status": statuses.get("news_permission_smoke", "not_run"),
            "known_limitations": (
                "Permission probe reports source access and fields only; it is not a narrative row source."
            ),
        },
    ]
